import redisCurrencyCodeDecimalsInserter, dataElementsSymbols,conversionRate,baseCurrency
redisCurrencyCodeDecimalsInserter.redisInserter()
dataElementsSymbols.dataElementInserter()
conversionRate.currrencyConvrsion()
baseCurrency.basecurrency()
